$Bug: Call of oclEmpty with Collection causes internal error$
$Category: OCL$
$State: Closed$
$BugAuthor: mk$
$Tests: test/t041$

use> ?oclEmpty(Collection(Integer))

INTERNAL ERROR: An unexpected exception occured. This happened most probably
due to an error in the program. The program will try to continue, but may
not be able to recover from the error. Please send a bug report to mr@tzi.org
with a description of your last input and include the following output:
Program version: 2.3.1
Project version: use 2-3-1-release.3 Wed, 02 Aug 2006 17:53:29 +0200 green
Stack trace: java.lang.NullPointerException
        at org.tzi.use.parser.SrcPos.<init>(SrcPos.java:42)
        at org.tzi.use.parser.SemanticException.<init>(SemanticException.java:51
)
        at org.tzi.use.parser.SemanticException.<init>(SemanticException.java:55
)
        at org.tzi.use.parser.ocl.ASTEmptyCollectionLiteral.gen(ASTEmptyCollecti
onLiteral.java:49)
        at org.tzi.use.parser.ocl.OCLCompiler.compileExpression(OCLCompiler.java
:68)
        at org.tzi.use.main.shell.Shell.cmdQuery(Shell.java:924)
        at org.tzi.use.main.shell.Shell.processLine(Shell.java:318)
        at org.tzi.use.main.shell.Shell.processLineSafely(Shell.java:254)
        at org.tzi.use.main.shell.Shell.run(Shell.java:205)
        at java.lang.Thread.run(Unknown Source)
